//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.9151
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// このソース コードは xsd によって自動生成されました。Version=2.0.50727.3038 です。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class PoseSet {

    private PoseSetPose[] poseField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Pose")]
    public PoseSetPose[] Pose {
        get {
            return this.poseField;
        }
        set {
            this.poseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class PoseSetPose {

    private string nameField;

    private decimal mvXField;

    private decimal mvYField;

    private decimal mvZField;

    private decimal rotBField;

    private decimal rotHField;

    private decimal rotPField;

    private decimal scXField;

    private decimal scYField;

    private decimal scZField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal mvX {
        get {
            return this.mvXField;
        }
        set {
            this.mvXField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal mvY {
        get {
            return this.mvYField;
        }
        set {
            this.mvYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal mvZ {
        get {
            return this.mvZField;
        }
        set {
            this.mvZField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal rotB {
        get {
            return this.rotBField;
        }
        set {
            this.rotBField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal rotH {
        get {
            return this.rotHField;
        }
        set {
            this.rotHField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal rotP {
        get {
            return this.rotPField;
        }
        set {
            this.rotPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal scX {
        get {
            return this.scXField;
        }
        set {
            this.scXField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal scY {
        get {
            return this.scYField;
        }
        set {
            this.scYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal scZ {
        get {
            return this.scZField;
        }
        set {
            this.scZField = value;
        }
    }
}
